Repository ruby/www.ruby-lang.org, pull requests merged in 2019-11, with the labels that each got.

#2242 Add rubytalk.org as additional archive to mailing list page (tr)
  tr/community/mailing-lists/index.md
Labels: content, translation

#2243 Update Turkish installation instructions (tr)
  tr/documentation/installation/index.md
Labels: content, translation

#2224 Translate CVE-2019-16201 post (tr)
  tr/news/_posts/2019-10-01-webrick-regexp-digestauth-dos-cve-2019-16201.md
Labels: news, translation

#2216 Translate "Ruby 2.5.6 Released" news (tr)
  tr/news/_posts/2019-08-28-ruby-2-5-6-released.md
Labels: news, translation

#2210 Translate "Security" page (tr)
  tr/security/index.md
Labels: content, translation

#2207 Update documentation page (tr)
  tr/documentation/index.md
Labels: content, translation

#2209 Update libraries page (tr)
  tr/libraries/index.md
Labels: content, translation

#2253 Update link in about page (tr)
  tr/about/index.md
Labels: content, translation

#2254 Update link in downloads page (tr)
  tr/downloads/index.md
Labels: content, translation

#2255 Update links in 2019-10-01 release posts (tr)
  tr/news/_posts/2019-10-01-ruby-2-4-8-released.md
  tr/news/_posts/2019-10-01-ruby-2-5-7-released.md
  tr/news/_posts/2019-10-01-ruby-2-6-5-released.md
Labels: news, translation

#2256 Fix a wrong translation (tr)
  tr/community/conferences/index.md
Labels: content, translation

#2259 Change faq links to en versions (tr)
  tr/community/mailing-lists/ruby-talk-guidelines/index.md
Labels: content, translation

#2269 Update 2019-03-05 post (ko)
  ko/news/_posts/2019-03-05-multiple-vulnerabilities-in-rubygems.md
  ko/news/_posts/2019-08-28-multiple-jquery-vulnerabilities-in-rdoc.md
Labels: news, translation

#2270 Translate 2019-10-01 news (ko)
  ko/news/_posts/2019-08-28-ruby-2-5-6-released.md
  ko/news/_posts/2019-10-01-code-injection-shell-test-cve-2019-16255.md
  ko/news/_posts/2019-10-01-http-response-splitting-in-webrick-cve-2019-16254.md
  ko/news/_posts/2019-10-01-nul-injection-file-fnmatch-cve-2019-15845.md
  ko/news/_posts/2019-10-01-ruby-2-4-8-released.md
  ko/news/_posts/2019-10-01-ruby-2-5-7-released.md
  ko/news/_posts/2019-10-01-ruby-2-6-5-released.md
  ko/news/_posts/2019-10-01-webrick-regexp-digestauth-dos-cve-2019-16201.md
Labels: news, translation

#2273 Update Silicon Valley Ruby Conference section (tr)
  tr/community/conferences/index.md
Labels: content, translation

#2274 Translate 2019-10-02 news (ko)
  ko/news/_posts/2019-10-02-ruby-2-4-9-released.md
Labels: news, translation

#2275 Remove unused Turkish IRC Channel (tr)
  tr/community/index.md
Labels: content

#2276 Translate Fukuoka Ruby Award 2020 (ko)
  ko/news/_posts/2019-10-16-fukuoka-ruby-award-2020.md
Labels: news, translation

#2285 Fix typo in 2.7.0-preview3 post (en)
  en/news/_posts/2019-11-23-ruby-2-7-0-preview3-released.md
Labels: all langs, news, typo

#2286 Translate ruby-2-7-0-preview3-released post (tr)
  tr/news/_posts/2019-11-23-ruby-2-7-0-preview3-released.md
Labels: news, translation

#2288 Follow the fix #2287 (tr)
  tr/news/_posts/2019-11-23-ruby-2-7-0-preview3-released.md
Labels: news
