Repository ruby/www.ruby-lang.org, pull requests merged in 2019-10, with the labels that each got.

#2146 Translate 2019-08-28 releases of Ruby (ko)
  ko/news/_posts/2019-08-28-multiple-jquery-vulnerabilities-in-rdoc.md
  ko/news/_posts/2019-08-28-ruby-2-4-7-released.md
  ko/news/_posts/2019-08-28-ruby-2-5-6-released.md
  ko/news/_posts/2019-08-28-ruby-2-6-4-released.md
Labels: news, translation

#2120 Rewrite information for installation using WSL (id)
  id/documentation/installation/index.md
Labels: content

#2130 Remove defunct conference sites (id)
  id/community/conferences/index.md
Labels: content, dead link

#2116 Update Ruby repository guide from Subversion to Git (id)
  id/community/ruby-core/index.md
Labels: content, feedback

#2180 Add Southeast Ruby to community/conferences (tr)
  tr/community/conferences/index.md
Labels: translation

#2187 Translate Ruby-Talk Guidelines page (tr)
  tr/community/mailing-lists/ruby-talk-guidelines/index.md
Labels: content, translation

#2181 Translate community/mailing-lists/manual-instructions (tr)
  tr/community/mailing-lists/manual-instructions/index.md
Labels: content, translation

#2200 Fix a wrong sentence
  tr/documentation/installation/index.md
Labels: content, translation

#2205 Review "Success Stories" page (tr)
  tr/documentation/success-stories/index.md
Labels: content, translation

#2204 Update "Ruby From Other Languages" pages (tr)
  tr/documentation/ruby-from-other-languages/index.md
  tr/documentation/ruby-from-other-languages/to-ruby-from-c-and-cpp/index.md
  tr/documentation/ruby-from-other-languages/to-ruby-from-java/index.md
  tr/documentation/ruby-from-other-languages/to-ruby-from-perl/index.md
  tr/documentation/ruby-from-other-languages/to-ruby-from-php/index.md
  tr/documentation/ruby-from-other-languages/to-ruby-from-python/index.md
Labels: content, translation

#2203 Update quickstart (tr)
  tr/documentation/quickstart/2/index.md
  tr/documentation/quickstart/3/index.md
  tr/documentation/quickstart/4/index.md
  tr/documentation/quickstart/index.md
Labels: content, translation

#2199 Translate conduct page tr
  tr/conduct/index.md
Labels: content, translation

#2193 Translate community/weblogs page (tr)
  tr/community/weblogs/index.md
Labels: content, translation

#2192 Translate community/user-groups (tr)
  tr/community/user-groups/index.md
Labels: content, translation

#2191 Translate community/ruby-core page (tr)
  tr/community/ruby-core/index.md
Labels: content, translation

#2189 Translate community/podcasts page (tr)
  tr/community/podcasts/index.md
Labels: content, translation

#2178 Remove defunct RubyNation website from the EN version
  en/community/conferences/index.md
Labels: all langs, content, dead link

#2190 Translate community/ruby-core/writing-patches (tr)
  tr/community/ruby-core/writing-patches/index.md
Labels: content, translation

#2208 Remove out-of-date info from downloads page (tr)
  tr/downloads/index.md
Labels: translation

#2212 Add DEV link to blog page (tr)
  tr/community/weblogs/index.md
Labels: content, translation

#2213 Remove defunct RubyNation website (tr)
  tr/community/conferences/index.md
Labels: content, translation

#2214 Translate multiple jquery vulnerabilities in rdoc (tr)
  tr/news/_posts/2019-08-28-multiple-jquery-vulnerabilities-in-rdoc.md
Labels: news, translation

#2215 Translate "Ruby 2.4.7 Released" news (tr)
  tr/news/_posts/2019-08-28-ruby-2-4-7-released.md
Labels: news, translation

#2217 Translate "Ruby 2.6.4 Released" news (tr)
  tr/news/_posts/2019-08-28-ruby-2-6-4-released.md
Labels: news, translation

#2211 Review and update old news (tr)
  tr/news/_posts/2007-09-18-euruko-2007-the-european-ruby-conference.md
  tr/news/_posts/2008-10-28-ruby-1-9-1-preview-1-released.md
  tr/news/_posts/2010-08-18-ruby-1-9-2-released.md
  tr/news/_posts/2010-12-25-ruby-1-8-7-p330-released.md
  tr/news/_posts/2010-12-25-ruby-1-9-2-p136-is-released.md
  tr/news/_posts/2013-11-22-heap-overflow-in-floating-point-parsing-cve-2013-4164.md
  tr/news/_posts/2013-12-25-ruby-2-1-0-is-released.md
  tr/news/_posts/2014-07-26-rubykaigi-2014-registration-online.md
  tr/news/_posts/2014-09-18-ruby-2-2-0-preview1-released.md
  tr/news/_posts/2014-09-19-ruby-2-0-0-p576-is-released.md
  tr/news/_posts/2014-09-19-ruby-2-1-3-is-released.md
  tr/news/_posts/2018-12-25-ruby-2-6-0-released.md
  tr/news/_posts/2019-01-30-ruby-2-6-1-released.md
  tr/news/_posts/2019-03-13-ruby-2-5-4-released.md
  tr/news/_posts/2019-03-13-ruby-2-6-2-released.md
  tr/news/_posts/2019-03-15-ruby-2-5-5-released.md
  tr/news/_posts/2019-04-01-ruby-2-4-6-released.md
  tr/news/_posts/2019-04-17-ruby-2-6-3-released.md
  tr/news/_posts/2019-05-30-ruby-2-7-0-preview1-released.md
Labels: news, translation

#2218 Translate "A code injection vulnerability of Shell#[]... news (tr)
  tr/news/_posts/2019-10-01-code-injection-shell-test-cve-2019-16255.md
Labels: news, translation

#2219 Translate "HTTP response splitting in WEBrick (Additional fix)" news (tr)
  tr/news/_posts/2019-10-01-http-response-splitting-in-webrick-cve-2019-16254.md
Labels: news, translation

#2221 Translate "Ruby 2.4.8 Released" news (tr)
  tr/news/_posts/2019-10-01-ruby-2-4-8-released.md
Labels: news, translation

#2222 Translate "Ruby 2.5.7 Released" news (tr)
  tr/news/_posts/2019-10-01-ruby-2-5-7-released.md
Labels: news, translation

#2223 Translate "Ruby 2.6.5 Released" news (tr)
  tr/news/_posts/2019-10-01-ruby-2-6-5-released.md
Labels: news, translation

#2226 Translate "2020 Fukuoka Ruby Award Competition" news (tr)
  tr/news/_posts/2019-10-16-fukuoka-ruby-award-2020.md
Labels: news, translation

#2233 Update translation of community/mailing-lists (ko)
  ko/community/mailing-lists/index.md
Labels: content, translation

#1605 Adding To Ruby from Python (es)
  es/documentation/ruby-from-other-languages/index.md
  es/documentation/ruby-from-other-languages/to-ruby-from-python/index.md
Labels: content, feedback, translation

#2220 Translate "A NUL injection vulnerability of File.fnmatch..." news (tr)
  tr/news/_posts/2019-10-01-nul-injection-file-fnmatch-cve-2019-15845.md
Labels: news, translation

#2225 Translate "Ruby 2.4.9 Released" news (tr)
  tr/news/_posts/2019-10-02-ruby-2-4-9-released.md
Labels: news, translation

#2227 Translate "Ruby 2.7.0-preview2 Released" news (tr)
  tr/news/_posts/2019-10-22-ruby-2-7-0-preview2-released.md
Labels: news, translation
